### ISSUE TITLE
Fetch PINCODE from MAP

### ISSUE THREAD

**Issue by MadhubratPatra** [sahil290791/sahiyogi#5]
## Description 

As a Sahiyogi user, when I drag the pointer over the map and click on a particular area, fetch the PINCODE based on the click and show me the related COVID19 information.
If using fullscreen, once the user selects the location, collapse the map and show the COVID info based on the PINCODE obtained

## Task

* [ ] Fetch the PINCODE based on the click done by the user on the map
* [ ] Add this text above the map : "You can also use the map to select your location, please drag across the map and click on your location. Please use the zoom in and zoom out feature by using the fullscreen mode of the map"
* [ ] When using Fullscreen mode, once the location is selected, collapse the fullscreen mode and show the information based on the PINCODE fetched

@sahil290791
