### ISSUE TITLE
Checklist for GoLive

### ISSUE THREAD

**Issue by MadhubratPatra** [sahil290791/sahiyogi#7]
Should have:

* [ ] Add ward wise zone details
* [ ] Feedback form
* [ ] Adding GA event details for the page
* [ ] Statewise and Location wise Lab listing

Nice to have:

* [ ] FAQs based on most searched questions in Google (eg: Liquor is going to be allowed in a few zones)
* [ ] Can I move out of my zone? : Based on zone restrictions finding out feasibility of going beyond zone limits

@sahil290791 @ambhu3916
